import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Goodwill",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`bg-slate-300 dark:bg-gray-950 ${inter.className}`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <main className="flex min-h-screen flex-col bg-slate-300 dark:bg-gray-950">
                        <>{children}</>
                    </main>
                </ThemeProvider>
            </body>
        </html>
    );
}
